# Generated by Django 5.1.3 on 2024-12-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marker',
        ),
        migrations.RenameField(
            model_name='battle',
            old_name='year',
            new_name='century',
        ),
        migrations.RenameField(
            model_name='battle',
            old_name='latitude',
            new_name='location_lat',
        ),
        migrations.RenameField(
            model_name='battle',
            old_name='longitude',
            new_name='location_lon',
        ),
        migrations.AddField(
            model_name='battle',
            name='date',
            field=models.DateField(default='1700-01-01'),
            preserve_default=False,
        ),
    ]
